sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_install:
  - cd 16_RestASPNET_Docker/RestASPNET/
  - echo "We are in the right folder"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provide: script
  script:
    docker tag rest-asp-net:latest $DOCKER_USERNAME/rest-asp-net:$TRAVIS_JOB_ID;
    docker tag rest-asp-net-db:latest $DOCKER_USERNAME/rest-asp-net-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-asp-net:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-asp-net-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email:false