version: '3.4'

services:
  db:
    image: rest-asp-net-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: fts99@ts-db-server
      MYSQL_USER: fts99@ts-db-server
      MYSQL_PASSWORD: Admin123!
      MYSQL_DATABASE: rest_asp_net
    ports:
      - 3308:3306
    networks:
      - udemy-network
      
  rest-asp-net:
    image: rest-asp-net
    build:
      context: .
      dockerfile: RestASPNET/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
    
